#!/usr/bin/bash -e

# Automate MariaDB setup
# Author: Christopher Markieta

# Credits: Sleavely
# http://stackoverflow.com/users/354776/sleavely

MY_DIR=$(dirname $0)

if [ $(id -u) -ne 0 ]; then
    echo "Permission denied"
    echo "Root privileges are required for running $0."
    exit 1
fi

password=''

while true
do
    echo -n 'New password: '
    read -s password
    echo -en '\nRe-enter new password: '
    read -s check
    echo
    if [ "$password" == "$check" ]; then
        break
    else
        echo 'Passwords do not match!'
    fi
done

# Make sure that NOBODY can access the server without a password
mysql -e "UPDATE mysql.user SET Password = PASSWORD("$password") WHERE User = 'root'"
# Kill the anonymous users
mysql -e "DROP USER ''@'localhost'"
# Because our hostname varies we'll use some Bash magic here.
mysql -e "DROP USER ''@'$(hostname)'"
# Kill off the demo database
mysql -e "DROP DATABASE test"
# Make our changes take effect
mysql -e "FLUSH PRIVILEGES"
