#!/usr/bin/bash -e

# Automate MariaDB setup
# Author: Christopher Markieta

# Credits: Sleavely
# http://stackoverflow.com/users/354776/sleavely

currentPassword=''
    newPassword=''

while true
do
    echo -n 'Enter current password for root (enter for none): '
    read -s currentPassword
    echo # Creates newline
    
    if [ $(mysql -h localhost -u root -p"$currentPassword") -eq 0 ]; then break
    else echo -e 'Incorrect password!\n'
    fi
done

while true
do
    echo -n 'New password: '
    read -s newPassword

    echo -en '\nRe-enter new password: '
    read -s check
    echo # Creates newline

    if [ "$newPassword" == "$check" ]; then break
    else echo -e 'Passwords do not match!\n'
    fi
done

# Make sure that NOBODY can access the server without a password
mysql -p"$currentPassword" -e "UPDATE mysql.user SET Password = PASSWORD("$newPassword") WHERE User = 'root'"
# Kill the anonymous users
mysql -p"$currentPassword" -e "DROP USER ''@'localhost'"
# Because our hostname varies we'll use some Bash magic here.
mysql -p"$currentPassword" -e "DROP USER ''@'$(hostname)'"
# Kill off the demo database
mysql -p"$currentPassword" -e "DROP DATABASE test"
# Make our changes take effect
mysql -p"$currentPassword" -e "FLUSH PRIVILEGES"
