#!/usr/bin/bash -e

# Automate MariaDB setup
# Author: Christopher Markieta

# Credits: Sleavely
# http://stackoverflow.com/users/354776/sleavely

MY_DIR=$(dirname $0)

if [ $(id -u) -ne 0 ]; then
    echo "Permission denied"
    echo "Root privileges are required for running $0."
    exit 1
fi

# Make sure that NOBODY can access the server without a password
mysql -e "UPDATE mysql.user SET Password = PASSWORD('CHANGEME') WHERE User = 'root'"
# Kill the anonymous users
mysql -e "DROP USER ''@'localhost'"
# Because our hostname varies we'll use some Bash magic here.
mysql -e "DROP USER ''@'$(hostname)'"
# Kill off the demo database
mysql -e "DROP DATABASE test"
# Make our changes take effect
mysql -e "FLUSH PRIVILEGES"
# Any subsequent tries to run queries this way will get access denied because lack of usr/pwd param
